### ISSUE TITLE
AMC-BLDC - add  IPTS test support w/ temporary test jig

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#34]
## Task description
Following #33 we need to start adding test support in IPTS starting from the temporary test jig.

## Definition of Done
- [x] Temporary test support added and tested

cc @Nicogene  @pattacini

**Comment by davidetome** [comment]
Started adding test support : 

- https://github.com/icub-tech-iit/ipts/compare/master...fix/%2334

cc @Nicogene

**Comment by davidetome** [comment]
Added test support, I will test it tomorrow w/ the setup : 

- https://github.com/icub-tech-iit/ipts/commits/fix/%2334/

cc @Nicogene @fgarini @maggia80

**Comment by davidetome** [comment]
Support added :and tested :  

- https://github.com/icub-tech-iit/ipts/commit/7be2d4c03a3269a8bb0e94fe660edc742fba61df

![ipts-amc-bldc](https://github.com/icub-tech-iit/ipts/assets/6638215/89da7f59-64d7-48b7-b939-43fd70aeeaad)


cc @Nicogene @maggia80

**Comment by davidetome** [comment]
Done w/ this PR : 

- https://github.com/icub-tech-iit/ipts/pull/35

cc @Nicogene @pattacini

**Comment by fgarini** [comment]
great @davidetome! Let me give you a quick update and a suggestion:
In order to test the PWM outputs, while we wait for the official AMCxJIG do you think it may help if we use the part of the AUX-AMC-TEST (just arrived) that implements a similar burden (47R instead of 22R, with series inductance)?
I can provide support on this.
